server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


#okta configuration
okta:
  oauth2:
    issuer: https://dev-24013644.okta.com/oauth2/default
    audience: api://default